apiVersion: v1
kind: Secret
type: kubernetes.io/dockerconfigjson
metadata:
  namespace: jobpoolv2
  name: aliyun
data:
  .dockerconfigjson: eyJhdXRocyI6eyJyZWdpc3RyeS5jbi1iZWlqaW5nLmFsaXl1bmNzLmNvbSI6eyJ1c2VybmFtZSI6InpoZW5nd2VpQDEyODA4MzY4MTUyMjg4NDYiLCJwYXNzd29yZCI6InpoZW5nd2VpMTIzIiwiYXV0aCI6ImVtaGxibWQzWldsQU1USTRNRGd6TmpneE5USXlPRGcwTmpwNmFHVnVaM2RsYVRFeU13PT0ifX19
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: jobpoolv2-pv-1
  namespace: jobpoolv2
spec:
  capacity:
    storage: 5Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Delete
  storageClassName: local-storage
  local:
    path: /data/jobpool-v2-develop
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values:
                -  k8s-worker1
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: jobpoolv2-pv-2
  namespace: jobpoolv2
spec:
  capacity:
    storage: 5Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Delete
  storageClassName: local-storage
  local:
    path: /data/jobpool-v2-develop
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values:
                -  k8s-worker2
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: jobpoolv2-pv-3
  namespace: jobpoolv2
spec:
  capacity:
    storage: 5Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Delete
  storageClassName: local-storage
  local:
    path: /data/jobpool-v2-develop
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values:
                -  k8s-worker3
---
kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: local-storage
  namespace: jobpoolv2
provisioner: kubernetes.io/no-provisioner
volumeBindingMode: WaitForFirstConsumer
---
apiVersion: v1
kind: Service
metadata:
  name: jobpool-handless
  namespace: jobpoolv2
  labels:
    app: jobpool2
spec:
  clusterIP: None
  ports:
    - port: 2380
      name: peer
    - port: 2379
      name: client
  selector:
    app: jobpool2
  publishNotReadyAddresses: true
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  labels:
    app: jobpool2
  name: jobpool2
  namespace: jobpoolv2
spec:
  replicas: 3
  serviceName: jobpool-handless
  selector:
    matchLabels:
      app: jobpool2
  template:
    metadata:
      labels:
        app: jobpool2
    spec:
      imagePullSecrets:
        - name: aliyun
      containers:
        - name: jobpool2
          image: registry.cn-beijing.aliyuncs.com/yunli-data-platform/jobpool-v2:2.0.1-SNAPSHOT.x86_64
          imagePullPolicy: Always
          resources:
            limits:
              memory: "800Mi"
            requests:
              memory: "128Mi"
          ports:
            - containerPort: 2380
            - containerPort: 2379
          env:
            - name: MY_POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: CLUSTER_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: HOST_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
            - name: ETCD_LOG_LEVEL
              value: "info"
            - name: SERVICE_NAME
              value: "jobpool-handless"
            - name: INITIAL_CLUSTER
              value: "jobpool2-0=http://jobpool2-0.jobpool-handless.jobpoolv2.svc.cluster.local:2380,jobpool2-1=http://jobpool2-1.jobpool-handless.jobpoolv2.svc.cluster.local:2380,jobpool2-2=http://jobpool2-2.jobpool-handless.jobpoolv2.svc.cluster.local:2380"
            - name: ETCD_INITIAL_CLUSTER_TOKEN
              value: "jobpool2-0"
            - name: ETCD_INITIAL_CLUSTER_STATE
              value: "new"
            - name: ETCD_EXPERIMENTAL_WARNING_APPLY_DURATION
              value: "500ms"
            - name: ETCD_JOB_PARALLELISM_LIMIT
              value: "500"
            - name: ETCD_HEARTBEAT_INTERVAL
              value: "200"
          volumeMounts:
            - name: datadir
              mountPath: /home/jobpool
      terminationGracePeriodSeconds: 30
  volumeClaimTemplates:
  - metadata:
      name: datadir
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 1Gi
      storageClassName: local-storage
---
apiVersion: v1
kind: Service
metadata:
  namespace: jobpoolv2
  name: jobpool-cluster-service
spec:
  ports:
    - nodePort: 30088
      port: 2379
      protocol: TCP
      targetPort: 2379
  selector:
    app: jobpool2
  sessionAffinity: None
  type: NodePort