FROM --platform=linux/amd64 ubuntu:18.04

WORKDIR /var/jobpool/
WORKDIR /var/lib/jobpool/

RUN apt-get update && apt-get install -y --no-install-recommends \
         wget \
         tzdata \
         curl

# timezone
ENV TZ=Asia/Shanghai
RUN ln -sf /usr/share/zoneinfo/Asia/Shanghai /etc/localtime
RUN echo 'Asia/Shanghai' >/etc/timezone
