FROM alpine

ADD jobpool_agent /usr/local/bin/
ADD jobpoolctl /usr/local/bin/

WORKDIR /var/jobpool/
WORKDIR /var/lib/jobpool/
WORKDIR /etc/jobpool/

RUN chmod +x /usr/local/bin/jobpool_agent
RUN chmod +x /usr/local/bin/jobpoolctl

CMD ["/usr/local/bin/jobpool_agent"]